name: Update README with Images

on:
  schedule:
    - cron: "0 * * * *" # every hour
  workflow_dispatch: # manual run
  push: # also run when code changes
    paths:
      - "scripts/**"
      - ".github/workflows/update-readme.yml"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install node-fetch@3

      - name: Run update script
        run: node scripts/update-readme.js

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update README with images from API" || echo "No changes"
          git push
